version: "3"

volumes:
  postgres:
    driver: local
services:
  db:
    image: postgres
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGDATA=pgdata
    volumes:
      - postgres:/var/lib/postgresql/data
  web:
    build: .
    ports:
      - "4001:4001"
    volumes:
      - .:/code
    depends_on:
      - db